### ISSUE TITLE
デザイン案の作成

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/SekigaeService#13]
# 概要

まだ作成できていないデザインをfigmaにて作成

# 改善の背景

# 要件

- userのマイページ
- etc (後で追加)

# 検討事項

- 

# 実装方針

- https://www.figma.com/file/shAahKWae9uDty6d1Pwwe9/Sekigae?node-id=32%3A0

# テスト項目

-

**Comment by RAINeko256** [comment]
@kathmandu777  @lemonadern 
マイページと席替えシートのデザイン案できました.
マイページ開いたとき、デフォルトで名簿の一覧を開いている想定です.
細かい(特定の場所の)指摘等あればFigmaのコメント機能を活用してもらえるとありがたいです🙏

よろしくおねがいします🙇‍♂️
https://www.figma.com/file/shAahKWae9uDty6d1Pwwe9/Sekigae?node-id=32%3A0

**Comment by RAINeko256** [comment]
@kathmandu777  @lemonadern 
ルーティングのURLつけ終わった
あと、席替えを行うところも考えてみた
名簿、前席の指定、座席の形、それぞれ選択ボタンを押すと右側のメニューに一覧が表示されるイメージです

**Comment by kathmandu777** [comment]
@RAINeko256 
LGTM

たいしがOKだと思ったらissueクローズで

**Comment by lemonadern** [comment]
@RAINeko256 LGTMmmmm
