### ISSUE TITLE
pug or slim or html

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/SekigaeService#15]
# 概要

htmlを書き出すのにどれを使うか検討する

# 改善の背景

# 要件

# 検討事項

- 

# 実装方針

- 

# テスト項目

-

**Comment by kathmandu777** [comment]
@lemonadern 
@Ichigo-dev

**Comment by lemonadern** [comment]
そんなに学習コスト高くないと思うのでどちらでもよいな...

**Comment by kathmandu777** [comment]
独断でpugとします。
