### ISSUE TITLE
埋め込みでReactを使えるようにする

### ISSUE THREAD

**Issue by lemonadern** [youngeek-0410/SekigaeService#2]
# 概要
- 埋め込み形式でReactを書けるようにする

# 改善の背景
- ページの一部をリッチでリアクティブな挙動にしたい

# 要件
- Reactを書いたらDjango上で反映されるようにする

# 検討事項
- Dockerを用いること

# 実装方針

- webpackで決まった場所に出力する

**Comment by lemonadern** [comment]
https://github.com/lemonadern/react-in-django-template
Docker無しバージョン

**Comment by lemonadern** [comment]
@kathmandu777 
webpackわかってきたらディレクトリ構成は結構柔軟に行けるなと思ったんですが、構成の希望があれば聞きたいかな
一応templateまではdjangoの機能だし、マンズが気持ち悪くない構成にしときたい

**Comment by kathmandu777** [comment]
今日コール出来れば話して決めたい

**Comment by kathmandu777** [comment]
@lemonadern

**Comment by lemonadern** [comment]
@kathmandu777 コールできる、スマホからだけど

**Comment by kathmandu777** [comment]
https://marsquai.com/745ca65e-e38b-4a8e-8d59-55421be50f7e/05f253f8-c11b-4c91-8091-989eb2600a7b/05ba6c42-d9b3-4861-b1d5-f17d1bd50e68/#h3-478aabed-97b3-4472-83c8-176744e810c4-606c3660-abb1-4e8c-8441-7d82bd2f7b9b

**Comment by lemonadern** [comment]
ディレクトリ構成：
#28 #29

**Comment by lemonadern** [comment]
templateのパスとstaticファイルのパスを指定

**Comment by lemonadern** [comment]
コミットわけすぎた
