### ISSUE TITLE
session appの作成

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/SekigaeService#4]
# 概要

セッション管理用のアプリを作成。

# 改善の背景

# 要件

# 検討事項

- ~~ログイン実装（google, twitter, github, facebook, email, e.t.c）~~

# 実装方針

- google認証まわりはfirebase

# テスト項目

- [ ]

**Comment by kathmandu777** [comment]
@lemonadern 
@Ichigo-dev 
検討事項の確認をよろしくお願いします。

**Comment by lemonadern** [comment]
「Google認証だけ」推しです

**Comment by Ichigo-dev** [comment]
github, facebook, twitter はなしだなあ、
google認証だけあり、でもそのうち有料になるな
VPSとかと一緒で全員で月で割ってもいいけど

**Comment by kathmandu777** [comment]
@Ichigo-dev 
google認証って有料になるんですか？

俺もgoogle認証推し

**Comment by Ichigo-dev** [comment]
割と無料枠多いけど、一応有料。
色々グーグル認証する方法があって、GCPプロジェクト作ってそのクライアントID取得して、SDKなりAPIなり頑張る方法か、
FirebaseのAuthenticationでグーグル認証を有効化して使う方法か。
おれ的には後者がおすすめ。
せっかくやるならお金かかってもしっかりやりたいね。

**Comment by kathmandu777** [comment]
### 結論
認証方法はgoogle認証のみ
google認証の実装についてはfirebaseを利用

**Comment by kathmandu777** [comment]
https://www.geeksforgeeks.org/how-to-create-a-new-project-in-django-using-firebase-database/

**Comment by kathmandu777** [comment]
https://medium.com/@canadiyaman/how-to-use-firebase-with-django-project-34578516bafe

**Comment by kathmandu777** [comment]
上のやつ違うわ
https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine?hl=ja

**Comment by kathmandu777** [comment]
https://www.geeksforgeeks.org/django-authentication-project-with-firebase/

**Comment by lemonadern** [comment]
https://www.notion.so/youngeekmaster/2528d0bfe4cc4fe1a00f59ab611f6241
これ更新してほしいかも

**Comment by kathmandu777** [comment]
> https://www.notion.so/youngeekmaster/2528d0bfe4cc4fe1a00f59ab611f6241
> これ更新してほしいかも

更新しました！現状での予定です。 @lemonadern

**Comment by kathmandu777** [comment]
https://www.mindbowser.com/implementation-of-social-authentication-by-using-firebase-with-django-rest-framework/

一番似ている気がする

**Comment by kathmandu777** [comment]
DRFだけど
https://www.oscaralsing.com/firebase-authentication-in-django/

**Comment by kathmandu777** [comment]
https://qiita.com/shitikakei/items/f2c3dd12dc10c8960802#django-%E3%81%A7%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF%E3%82%92%E4%BD%BF%E3%81%86%E3%81%93%E3%81%A8%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E3%81%AE%E8%80%83%E3%81%88%E6%96%B9

**Comment by kathmandu777** [comment]
https://nwpct1.hatenablog.com/entry/django-auth-patterns

**Comment by kathmandu777** [comment]
### Django Official Docs (customize authentication)
https://docs.djangoproject.com/ja/3.2/topics/auth/customizing/

**Comment by kathmandu777** [comment]
allauthのカスタマイズ認証クラス

https://github.com/pennersr/django-allauth/blob/master/allauth/account/auth_backends.py

**Comment by kathmandu777** [comment]
- [ ] AUTHENTICATIONS_BACKENDSにfirebase authを含める

**Comment by kathmandu777** [comment]
firebase 公式docs
https://firebase.google.com/docs/web/setup?hl=ja

**Comment by kathmandu777** [comment]
**firebase auth google official docs**
https://firebase.google.com/docs/auth/web/google-signin?hl=ja

**Comment by kathmandu777** [comment]
railsを用いたfirebase認証
https://qiita.com/johnslith/items/6f8742b786b50f8dc0ac

**Comment by kathmandu777** [comment]
Firebase Authentication を利用した認証システムの実装 (フロントのみの実装 only js)

https://qiita.com/TakeshiNickOsanai/items/7eed1ca8b9e482d392bc

**Comment by kathmandu777** [comment]
認証バックエンドをカスタマイズしてログイン方法を変更する

https://django.kurodigi.com/customize-auth-backend/

**Comment by kathmandu777** [comment]
loginが必要

https://stackoverflow.com/questions/66397239/how-do-i-set-my-authentication-backend-as-default-in-settings-py-file-of-my-djan
https://qiita.com/knakajima3027/items/34b2a105da7cdb411736

**Comment by kathmandu777** [comment]
django redirect with ajax

https://awesome-linus.com/2019/04/03/django-return-redirect-and-redirect-js/
