### ISSUE TITLE
signin signout header

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/SekigaeService#41]
# 概要

signinとsingoutボタンのあるヘッダーを作成する。

# 改善の背景

現在はjsで書かれているのでreactを用いてリファクタしてほしい。

# 要件

# 検討事項

- 

# 実装方針

- temp-indexを参考にする。

# テスト項目

-

**Comment by lemonadern** [comment]
html elementをラップしてコンポーネントを作る場合の型情報について参考になりそうな記事
- https://qiita.com/Ushinji/items/9b681b786d7474350381
- https://qiita.com/Yametaro/items/814f40d08e9d30584e20
