### ISSUE TITLE
eslint の導入

### ISSUE THREAD

**Issue by lemonadern** [youngeek-0410/SekigaeService#47]
# 概要

- frontend に ( eslint / prettier ) を導入したい

# 改善の背景

- 共通したスタイル規則を導入する

# 要件

-

# 検討事項

- 

# 実装方針

-

**Comment by kathmandu777** [comment]
https://github.com/youngeek-0410/SekigaeService/pull/94
https://github.com/youngeek-0410/SekigaeService/pull/90

関連PR
