### ISSUE TITLE
備考をPRテンプレートに追加

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/SekigaeService#87]
# 概要

PRテンプレート内に
```
# 備考
```
が欲しい

# 改善の背景

@kathmandu777 が欲しい

# 要件

# 検討事項

- みんながいらないならcloseする。私は毎度タイプするようにします。

# 実装方針

- 

# テスト項目

-

**Comment by kathmandu777** [comment]
@lemonadern 
いるかどうか検討して実装お願いします。（実装ってほどじゃないけど）

**Comment by lemonadern** [comment]
まあ、あってもよい
